language: node_js
sudo: false
services:
  - xvfb
cache:
  directories:
    - bower_components
    - node_modules
node_js:
  - 8
install:
  - "yarn"
  - "gulp --production"
script:
  - "gulp hint"
  - "karma start"
