language: node_js
sudo: false
cache:
  directories:
    - bower_components
    - node_modules
node_js:
  - 8
install:
  - "yarn"
  - "gulp --production"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "gulp hint"
  - "karma start"
